### ISSUE TITLE
Inconsistent roll from the examples

### ISSUE THREAD

**Issue by Roms1383** [Geobert/caith#2]
Hello !
First and foremost, thanks for this library because it's really cool :)

Here's just a small issue I've found while trying out the [examples from the README](https://github.com/Geobert/caith#examples).

## Issue

There seems to be an issue with roll in the form of : `10d6 e6 K8 +4`.

## How to reproduce

**Cargo.toml**
```toml
[package]
name = "test-caith"
# ...
edition = "2018"

[dependencies]
caith = "2.2.0"
```

**src/main.rs**
```rust
use caith::{Roller};
fn main() {
  println!("2d6 + 3d10    => {}", Roller::new("2d6 + 3d10").unwrap().roll().unwrap());
  println!("3d6 + 5       => {}", Roller::new("3d6 + 5").unwrap().roll().unwrap());
  println!("3d6 e6        => {}", Roller::new("3d6 e6").unwrap().roll().unwrap());
  println!("3d6           => {}", Roller::new("3d6!").unwrap().roll().unwrap());
  println!("3d10 d1       => {}", Roller::new("3d10 d1").unwrap().roll().unwrap());
  println!("4d6 r2        => {}", Roller::new("4d6 r2").unwrap().roll().unwrap());
  println!("4d6 ir2       => {}", Roller::new("4d6 ir2").unwrap().roll().unwrap());
  println!("6d10 t7       => {}", Roller::new("6d10 t7").unwrap().roll().unwrap());
  println!("5d10 t8 f1    => {}", Roller::new("5d10 t8 f1").unwrap().roll().unwrap());
  println!("4d10 k3       => {}", Roller::new("4d10 k3").unwrap().roll().unwrap());
  println!("10d6 e6 K8 +4 => {}", Roller::new("10d6 e6 K8 +4").unwrap().roll().unwrap()); // <= this is the line that has an issue
}
```

## Expected
That it rolls some 10d6 while exploding on 6 once, keeping the 8 highest rolls and adding 4 to the total.

## Ran repeatedly and got

*  either it panics like so :
    <img width="981" alt="Screen Shot 2020-11-23 at 12 54 24" src="https://user-images.githubusercontent.com/21016014/99932593-2175bb80-2d8b-11eb-84f4-623016b61748.png">

*  either it doesn't, but result is confusing :
    <img width="990" alt="Screen Shot 2020-11-23 at 12 51 39" src="https://user-images.githubusercontent.com/21016014/99932496-cba11380-2d8a-11eb-8e70-96b3ce8d8449.png">
    I might be wrong but result here is `44` while, from what I understood, it should be :
    *  all : `[5, 5, 5, 5, 4, 3, 3, 2, 1, 1] = 34`
    *  8 highest : `[5, 5, 5, 5, 4, 3, 3, 2] = 32`
    *  8 highest plus four : `36`

**Comment by Geobert** [comment]
Thank you for the report! I'll have a look at this asap :)
